=== zhangzijie/zhangzijie.github.io/download/downloadList.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT files (file+)>
<!ELEMENT file (name, type, size, description, link)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ATTLIST file id CDATA #REQUIRED>

=== zhangzijie/zhangzijie.github.io/download/downloadList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE files SYSTEM "downloadList.dtd">
<files>
    <file id="dl001">
		<name>XHTML参考手册</name>
        <type>chm</type>
        <size>287KB</size>
        <description>XHTML 参考手册</description>
        <link>ftp://ftpshare@115.28.147.43/xHTML参考手册.chm</link>
    </file>
	<file id="dl002">
		<name>HTML5参考手册</name>
        <type>chm</type>
        <size>194KB</size>
        <description>HTML5 参考手册</description>
        <link>ftp://ftpshare@115.28.147.43/w3c标准html5手册.chm</link>
    </file>
    <file id="dl003">
		<name>CSS 2.0参考手册</name>
        <type>chm</type>
        <size>258KB</size>
        <description>CSS 2.0 参考手册</description>
        <link>ftp://ftpshare@115.28.147.43/CSS2.0中文手册.chm</link>
    </file>
    <file id="dl004">
		<name>CSS 3.0参考手册</name>
        <type>chm</type>
        <size>380KB</size>
        <description>CSS 3.0 参考手册</description>
        <link>ftp://ftpshare@115.28.147.43/CSS3.0参考手册.chm</link>
    </file>
    <file id="dl005">
		<name>JavaScript核心参考手册</name>
        <type>chm</type>
        <size>300KB</size>
        <description>JavaScript核心参考手册  2008年版</description>
        <link>ftp://ftpshare@115.28.147.43/JavaScript核心参考手册.chm</link>
    </file>
    <file id="dl006">
		<name>JScript参考手册</name>
        <type>chm</type>
        <size>602KB</size>
        <description>JScript参考手册  2000年版</description>
        <link>ftp://ftpshare@115.28.147.43/JScript参考手册2000年版.chm</link>
    </file>
    <file id="dl007">
		<name>jQuery 1.4参考手册</name>
        <type>chm</type>
        <size>489KB</size>
        <description>jQuery 1.4参考手册</description>
        <link>ftp://ftpshare@115.28.147.43/jQuery1.4参考手册.CHM</link>
    </file>
    <file id="dl008">
		<name>jQuery 1.10参考手册</name>
        <type>chm</type>
        <size>399KB</size>
        <description>jQuery 1.10参考手册</description>
        <link>ftp://ftpshare@115.28.147.43/jQuery1.10参考手册.chm</link>
    </file>
    <file id="dl009">
		<name>Java 1.6中文手册</name>
        <type>chm</type>
        <size>35.12MB</size>
        <description>Java 1.6 API帮助文档 中文版</description>
        <link>ftp://ftpshare@115.28.147.43/Java1.6中文手册.CHM</link>
    </file>
    <file id="dl010">
		<name>PHP 2014中文手册</name>
        <type>chm</type>
        <size>18.18MB</size>
        <description>PHP 2014中文手册</description>
        <link>ftp://ftpshare@115.28.147.43/php中文手册.chm</link>
    </file>
    <file id="dl011">
		<name>SQL参考手册</name>
        <type>chm</type>
        <size>215KB</size>
        <description>Microsoft Jet SQL 参考</description>
        <link>ftp://ftpshare@115.28.147.43/SQL参考手册中文版.chm</link>
    </file>
    <file id="dl012">
		<name>ORACLE九阴真经</name>
        <type>chm</type>
        <size>62KB</size>
        <description>ORACLE九阴真经</description>
        <link>ftp://ftpshare@115.28.147.43/ORACLE九阴真经.chm</link>
    </file>
    <file id="dl013">
		<name>腾讯前端代码规范</name>
        <type>doc</type>
        <size>227KB</size>
        <description>腾讯AlloyTeam前端代码规范</description>
        <link>ftp://ftpshare@115.28.147.43/CodeGuideBy@AlloyTeam.doc</link>
    </file>
    <file id="dl014">
		<name>W3School离线手册</name>
        <type>chm</type>
        <size>12.94MB</size>
        <description>W3School离线手册 2014.7.8版</description>
        <link>ftp://ftpshare@115.28.147.43/W3School离线手册(2014.7.8).chm</link>
    </file>
	<file id="dl015">
		<name>Google Java编程风格指南</name>
        <type>chm</type>
        <size>287KB</size>
        <description>Google Java编程风格指南 中文版 2014.1.20</description>
        <link>ftp://ftpshare@115.28.147.43/GoogleJava编程风格指南.chm</link>
    </file>
	<file id="dl016">
		<name>Java Servlet 2.4 英文文档</name>
        <type>chm</type>
        <size>1.85MB</size>
        <description>Java Servlet 2.4 英文文档</description>
        <link>ftp://ftpshare@115.28.147.43/JavaServletDevelopmentKit2.4DocumenTation.chm</link>
    </file>
	<file id="dl017">
		<name>Apache2.2 中文手册</name>
        <type>chm</type>
        <size>1.32MB</size>
        <description>Apache2.2 中文手册</description>
        <link>ftp://ftpshare@115.28.147.43/Apache2.2中文手册.chm</link>
    </file>
	<file id="dl018">
		<name>Apache2.4 中文手册</name>
        <type>chm</type>
        <size>1.47MB</size>
        <description>Apache2.4 中文手册</description>
        <link>ftp://ftpshare@115.28.147.43/Apache2.4文档.chm</link>
    </file>
	<file id="dl019">
		<name>W3Cfuns前端开发工具箱</name>
        <type>exe</type>
        <size>1.67MB</size>
        <description>W3Cfuns前端开发工具箱</description>
        <link>ftp://ftpshare@115.28.147.43/W3Cfuns前端开发工具箱.exe</link>
    </file>
	<file id="dl020">
		<name>Oracle 9i SQL参考手册</name>
        <type>chm</type>
        <size>6.93MB</size>
        <description>Oracle 9i SQL参考手册</description>
        <link>ftp://ftpshare@115.28.147.43/Oracle9iSQL参考手册.chm</link>
    </file>
	<file id="dl021">
		<name>Linux常用命令大全</name>
        <type>chm</type>
        <size>363KB</size>
        <description>Linux常用命令大全</description>
        <link>ftp://ftpshare@115.28.147.43/Linux常用命令大全.chm</link>
    </file>
	<file id="dl022">
		<name>Linux基础命令教程</name>
        <type>chm</type>
        <size>1.22MB</size>
        <description>Linux基础命令教程</description>
        <link>ftp://ftpshare@115.28.147.43/Linux基础命令教程.chm</link>
    </file>
	<file id="dl023">
		<name>jQuery EasyUI 1.3.5 API中文版</name>
        <type>exe</type>
        <size>3.89MB</size>
        <description>jQuery EasyUI 1.3.5 API中文版</description>
        <link>ftp://ftpshare@115.28.147.43/jQueryEasyUI1.3.5API中文版.exe</link>
    </file>
	<file id="dl024">
		<name>mongodb入门教程</name>
        <type>chm</type>
        <size>1.47MB</size>
        <description>mongodb入门教程</description>
        <link>ftp://ftpshare@115.28.147.43/mongodb入门教程.chm</link>
    </file>
	<file id="dl025">
		<name>json lib 2.4 jdk1.5</name>
        <type>chm</type>
        <size>316KB</size>
        <description>net.sf.json包参考手册 json-lib-2.4-jdk1.5.chm</description>
        <link>ftp://ftpshare@115.28.147.43/json-lib-2.4-jdk1.5.chm</link>
    </file>
	<file id="dl026">
		<name>XStream Core 1.3 API</name>
        <type>chm</type>
        <size>890KB</size>
        <description>XStream Core 1.3 API com.thoughtworks.xstream包</description>
        <link>ftp://ftpshare@115.28.147.43/XStreamCore1.3API.CHM</link>
    </file>
	<file id="dl027">
		<name>J2EE 1.6 API英文版</name>
        <type>chm</type>
        <size>7.94MB</size>
        <description>J2EE 1.6 API英文版</description>
        <link>ftp://ftpshare@115.28.147.43/J2EE1.6API英文版.chm</link>
    </file>
	<file id="dl028">
		<name>struts 2.3.16.3 API</name>
        <type>chm</type>
        <size>1.72MB</size>
        <description>struts 2.3.16.3 API</description>
        <link>ftp://ftpshare@115.28.147.43/struts-2.3.16.3.chm</link>
    </file>
	<file id="dl029">
		<name>Hibernate 3.2 API英文版</name>
        <type>chm</type>
        <size>7.08MB</size>
        <description>Hibernate 3.2 API英文版</description>
        <link>ftp://ftpshare@115.28.147.43/Hibernate3.2API英文版.chm</link>
    </file>
	<file id="dl030">
		<name>spring 3.00 API英文版</name>
        <type>chm</type>
        <size>10.93MB</size>
        <description>spring 3.00 API英文版</description>
        <link>ftp://ftpshare@115.28.147.43/spring3.00API英文版.chm</link>
    </file>
</files>
